//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationUchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int LogId { get; set; }
        public Nullable<int> RentId { get; set; }
        public Nullable<int> ThenantId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> MallId { get; set; }
        public Nullable<int> PavilionId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> RentalStart { get; set; }
        public Nullable<System.DateTime> RentalEnd { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Malls Malls { get; set; }
        public virtual MallStatuses MallStatuses { get; set; }
        public virtual PavilionsLease PavilionsLease { get; set; }
        public virtual PavilionStatuses PavilionStatuses { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
