//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationUchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallsListView
    {
        public int MallId { get; set; }
        public string MallName { get; set; }
        public Nullable<int> PavilionsCount { get; set; }
        public string MallStatus { get; set; }
        public string CityName { get; set; }
        public Nullable<int> BuildingCost { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
        public Nullable<int> LevelsCount { get; set; }
        public byte[] MallPicture { get; set; }
    }
}
