//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationUchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Malls()
        {
            this.Pavilions = new HashSet<Pavilions>();
            this.PavilionsLease = new HashSet<PavilionsLease>();
        }
    
        public int MallId { get; set; }
        public string MallName { get; set; }
        public Nullable<int> MallStatusId { get; set; }
        public Nullable<int> PavilionsCount { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> BuildingCost { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
        public Nullable<int> LevelsCount { get; set; }
        public byte[] MallPicture { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual MallStatuses MallStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pavilions> Pavilions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PavilionsLease> PavilionsLease { get; set; }
    }
}
