//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationUchebka
{
    using System;
    using System.Collections.Generic;
    
    public partial class PavilionsInMalls
    {
        public int MallId { get; set; }
        public string MallName { get; set; }
        public int PavilionId { get; set; }
        public string PavilionNumber { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> SquareMeterCost { get; set; }
        public Nullable<double> ValueAddedFactor { get; set; }
        public string PavilionStatus { get; set; }
    }
}
